const data={
        en:{
            payment:'Payment History',
            tap:'Tap to view payment history',
            today:'Today',
            successful:'Payment Successful',
            failed:'Payment Failed',
            pending:'Pending',
            status:'Status:',
            price:'Reference price:',
            time:'Time of transaction:',
            method:'Payment method:',
            number:'Order number:',
            recorded:'Payment info is recorded in UTC time and only for your reference.',
            problems:'If you have problems paying, please contact Customer Support.',
            support:'Customer Support',
            coins:"@ Coins",
            details:"Details",
            cancel:"Cancel",
            confirm:"Confirm",
            days:"% Days #",
            month:"1 Month #",
            months:"% Months #",
            year:"1 Year #",
            lifeTime:"Lifetime #",
            sorry:"Sorry, something went wrong while loading. Please try again later.",
            refesh:"Refresh",
            noPayment:"No payment history",
            refreshBtn:"Refresh purchase status",
            verification:"Verification in progress…",
            refreshBtns:"Refresh purchase status (@s)",
            unsuccessful:"Payment unsuccessful",
            contact:"Please contact us if you have any questions.",
            ok:"OK",
            wait:"Please wait..."



        },
        ar:{
            payment:'محفوظات الدفع',
            tap:'انقر لعرض محفوظات الدفع',
            today:'اليوم',
            successful:'تم الدفع بنجاح',
            failed:'لقد فشلت عملية الدفع',
            pending:'قيد الانتظار',
            status:'الحالة:',
            price:'السعر المرجعي:',
            time:'وقت المعاملة:',
            method:'طريقة الدفع أو السداد:',
            number:'رقم الطلب:',
            recorded:'تُسجل معلومات الدفع وفقًا للتوقيت العالمي، وللرجوع إليها فقط.',
            problems:'إذا كان لديك مشاكل في الدفع، يرجى الاتصال بدعم العملاء.',
            support:'دعم العملاء',
            coins:"@ عملة",
            details:"تفاصيل",
            cancel:"إلغاء",
            confirm:"تأكيد",
            days:"% أيام #",
            month:"1 شهر #",
            months:"% أشهر #",
            year:"1 سنة #",
            lifeTime:"مدى الحياة #",
            sorry:"عذراً، حدث خطأ ما خلال التحميل. يُرجى المحاولة مجدداً في وقت لاحق.",
            refesh:"إعادة تحميل",
            noPayment:"لا يوجد محفوظات الدفع",
            refreshBtn:"تحديث حالة الشراء",
            verification:"جاري التحقق ...",
            refreshBtns:"تحديث حالة الشراء (@s)",
            unsuccessful:"عملية الدفع فشلت",
            contact:"يرجى الاتصال بنا إذا كان لديك أي أسئلة.",
            ok:"حسناً",
            wait:"يرجى الانتظار..."
        },
        tr:{
            payment:"Ödeme Geçmişi",
            tap:"Ödeme geçmişini görüntülemek için dokunun",
            today:"Bugün",
            successful:"Ödeme Başarılı",
            failed:"Ödeme Başarısız",
            pending:"Beklemede",
            status:"Durum:",
            price:'Referans fiyatı:',
            time:'İşlem zamanı:',
            method:'Ödeme yöntemi:',
            number:'Sipariş numarası:',
            recorded:'Ödeme bilgileri, UTC saatinde kaydedilir ve yalnızca sizin başvurmanız içindir.',
            problems:'Ödemeyle ilgili sorununuz varsa, lütfen Müşteri Destek ile iletişime geçin.',
            support:'Müşteri Destek',
            coins:"@ Jeton",
            details:"Detaylar",
            cancel:"İptal et",
            confirm:"Doğrula ",
            days:"% Gün #",
            month:"1 Ay #",
            months:"% Ay #",
            year:"1 Yıl #",
            lifeTime:"Ömür boyu #",
            sorry:"Üzgünüz, yükleme sırasında bir şeyler ters gitti. Lütfen daha sonra tekrar dene. ",
            refesh:"Yenile",
            noPayment:"Ödeme geçmişi yok",
            refreshBtn:"Satın alma durumunu yenile",
            verification:"Doğrulama sürüyor...",
            refreshBtns:"Satın alma durumunu yenile (@s)",
            unsuccessful:"Ödeme başarısız",
            contact:"Herhangi bir sorunuz varsa lütfen bizimle iletişime geçin.",
            ok:"TAMAM",
            wait:"Lütfen bekleyin..."
        },
        es:{
            payment:'Historial de pagos',
            tap:'Toca para ver el historial de pagos',
            today:'Hoy',
            successful:'Pago efectuado con éxito',
            failed:'Pago fallido',
            pending:'Pendiente',
            status:'Estado:',
            price:'Precio de referencia:',
            time:'Hora de la transacción:',
            method:'Método de pago:',
            number:'Número de pedido:',
            recorded:'La información de pago se registra en hora UTC y solo para su referencia.',
            problems:'Si tiene dificultades para efectuar el pago, póngase en contacto con el servicio de atención al cliente.',
            support:'atención al cliente',
            coins:"@ Monedas",
            details:"Detalles",
            cancel:"Cancelar",
            confirm:"Confirmar",
            days:"% días de #",
            month:"1 mes de #",
            months:"% meses de #",
            year:"1 año de #",
            lifeTime:"# de por vida",
            sorry:"Lo sentimos, algo ha salido mal mientras se cargaba. Inténtalo de nuevo más tarde.",
            refesh:"Recarga",
            noPayment:"Sin historial de pagos",
            refreshBtn:"Actualizar el estado de la compra",
            verification:"Verificación en curso…",
            refreshBtns:"Actualizar el estado de la compra (@s)",
            unsuccessful:"Pago fallido",
            contact:"Por favor, póngase en contacto con nosotros si tiene alguna pregunta.",
            ok:"Vale",
            wait:"Espera, por favor..."
            

        },
        in:{
            payment:"Riwayat Pembayaran",
            tap:"Ketuk untuk melihat riwayat pembayaran",
            today:"Hari ini",
            successful:"Pembayaran Berhasil",
            failed:"Pembayaran Gagal",
            pending:"Tertunda",
            status:"Status:",
            price:"Harga acuan:",
            time:"Waktu transaksi:",
            method:"Cara pembayaran:",
            number:"Nomor pesanan:",
            recorded:"Info pembayaran dicatat dalam waktu UTC dan hanya sebagai referensi.",
            problems:"Jika Anda mengalami masalah pembayaran, silakan hubungi Dukungan Pelanggan.",
            support:"Dukungan Pelanggan",
            coins:"@ Koin",
            details:"Detail",
            cancel:"Batalkan",
            confirm:"Konfirmasi",
            days:"# % Hari",
            month:"# 1 Bulan",
            months:"# % Bulan",
            year:"# 1 Tahun",
            lifeTime:"# Seumur Hidup",
            sorry:"Maaf, terjadi kesalahan saat memuat. Silakan coba lagi nanti.",
            refesh:"Segarkan",
            noPayment:"Tidak ada riwayat pembayaran",
            refreshBtn:"Muat ulang status pembelian",
            verification:"Verifikasi sedang berlangsung...",
            refreshBtns:"Muat ulang status pembelian (@s)",
            unsuccessful:"Pembayaran gagal",
            contact:"Silakan hubungi kami jika Anda memiliki pertanyaan.",
            ok:"Oke",
            wait:"Mohon tunggu..."

        },
        hi:{
            payment:"भुगतान इतिहास",
            tap:"भुगतान इतिहास देखने के लिए टैप करें",
            today:"आज",
            successful:"भुगतान सफल",
            failed:"भुगतान असफल हुआ",
            pending:"विचाराधीन",
            status:"स्थिति:",
            price:"रेफरेंस मूल्य:",
            time:"लेन-देन का समय:",
            method:"भुगतान का तरीका:",
            number:"क्रम संख्या:",
            recorded:"भुगतान की जानकारी UTC समय में दर्ज की गई है केवल आपके रेफरेंस के लिए।",
            problems:"यदि आपको भुगतान करने में समस्या है, तो कृपया ग्राहक सहायता से संपर्क करें।",
            support:"ग्राहक सहायता",
            coins:"@ कॉइन्स",
            details:"विवरण",
            cancel:"रद्द करना",
            confirm:"पुष्टि करें",
            days:"% दिनों हेतु #",
            month:"1 महीना हेतु #",
            months:"% महीने हेतु #",
            year:"1 साल हेतु #",
            lifeTime:"आजीवन #",
            sorry:"क्षमा करें, लोड करते में कुछ समस्या हुई है। बाद में पुन: प्रयास करें।",
            refesh:"ताज़ा करें",
            noPayment:"कोई भुगतान इतिहास नहीं",
            refreshBtn:"खरीद की स्थिति को रिफ्रेश करें",
            verification:"सत्यापन जारी है...",
            refreshBtns:"खरीद की स्थिति को रिफ्रेश करें (@s)",
            unsuccessful:"भुगतान असफल हुआ",
            contact:"यदि आपके कोई प्रश्न हैं तो कृपया हमसे से संपर्क करें।",
            ok:"ठीक है",
            wait:"कृपया प्रतीक्षा करें..."
        },
        de:{
            payment:"Zahlungshistorie",
            tap:"Antippen, um die Zahlungshistorie zu sehen",
            today:"Heute",
            successful:"Zahlung erfolgreich",
            failed:"Zahlung fehlgeschlagen",
            pending:"Ausstehend",
            status:"Status:",
            price:"Referenzpreis:",
            time:"Transaktionszeit:",
            method:"Zahlungsmethode:",
            number:"Bestellnummer:",
            recorded:"Zahlungsinformationen werden in UTC-Zeit und nur zu Ihrer Information erfasst.",
            problems:"Wenn Sie Probleme mit der Zahlung haben, kontaktieren Sie bitten den Kundenservice.",
            support:"Kundenservice",
            coins:"@ Münzen",
            details:"Einzelheiten",
            cancel:"Abbrechen",
            confirm:"Bestätigen",
            days:"# für % Tage",
            month:"# für 1 Monat",
            months:"# für % Monate",
            year:"# für 1 Jahr",
            lifeTime:"# lebenslang",
            sorry:"Entschuldigung, beim Laden ist ein Fehler aufgetreten. Bitte versuche es später erneut.",
            refesh:"Neuladen",
            noPayment:"Keine Zahlungshistorie",
            refreshBtn:"Einkaufsstatus aktualisieren",
            verification:"Verifizierung im Gange...",
            refreshBtns:"Einkaufsstatus aktualisieren (@s)",
            unsuccessful:"Bezahlung fehlgeschlagen",
            contact:"Bitte kontaktieren Sie uns, wenn Sie Fragen haben.",
            ok:"Okay",
            wait:"Bitte warten …"
        },
        fr:{
            payment:"Historique des paiements",
            tap:"Appuyez pour afficher l'historique des paiements",
            today:"Aujourd'hui",
            successful:"Paiement réussi",
            failed:"Paiement manqué",
            pending:"En attente",
            status:"Statut :",
            price:"Prix de référence:",
            time:"Heure de la transaction :",
            method:"Mode de paiement :",
            number:"Numéro de commande :",
            recorded:"Les données de paiement sont enregistrées en heure UTC, et uniquement à titre de référence.",
            problems:"Si vous rencontrez des problèmes lors du paiement, veuillez contacter le service client.",
            support:"service client",
            coins:"@ Pièces",
            details:"Détails",
            cancel:"Annuler",
            confirm:"Confirmer",
            days:"% jours #",
            month:"1 mois #",
            months:"% mois #",
            year:"1 an #",
            lifeTime:"# à vie",
            sorry:"Désolé, le chargement a échoué. Veuillez réessayer plus tard.",
            refesh:"Actualiser",
            noPayment:"Pas d'historique de paiement",
            refreshBtn:"Actualiser le statut de l'achat",
            verification:"Vérification en cours…",
            refreshBtns:"Actualiser le statut de l'achat (@s)",
            unsuccessful:"Paiement échoué",
            contact:"Contactez-nous si vous avez des questions.",
            ok:"D'accord",
            wait:"Merci de patienter..."
        },
        ja:{
            payment:"支払履歴",
            tap:"タップして支払い履歴を表示",
            today:"今日",
            successful:"支払い完了",
            failed:"支払い失敗",
            pending:"保留中",
            status:"状態：",
            price:"参考価格：",
            time:"取引時間：",
            method:"支払方法：",
            number:"注文番号：",
            recorded:"お支払い情報はUTC時間で記録され、お客様のご確認用のみの目的となります。",
            problems:"支払いに問題がありましたら、カスタマーサポートまでお問い合わせください。",
            support:"カスタマーサポート",
            coins:"@ コイン",
            details:"詳細",
            cancel:"キャンセル",
            confirm:"確定する",
            days:"%日間#",
            month:"1ヶ月#",
            months:"%ヶ月#",
            year:"1年間#",
            lifeTime:"生涯#",
            sorry:"ロード中に何らかのエラーが発生しました。後でもう一度お試しください。",
            refesh:"更新",
            noPayment:"支払い履歴なし",
            refreshBtn:"購入ステータを更新",
            verification:"認証を行っています…",
            refreshBtns:"購入ステータを更新（@s）",
            unsuccessful:"支払いできませんでした",
            contact:"不明な点などがありましたらお問い合わせください。",
            ok:"OK",
            wait:"お待ちください..."
        },
        zh:{
            payment:"付款紀錄",
            tap:"點擊查看付款紀錄",
            today:"今天",
            successful:"付款成功",
            failed:"付款失敗",
            pending:"待定中",
            status:"狀態：",
            price:"參考價格：",
            time:"交易時間：",
            method:"付款方式：",
            number:"訂單編號：",
            recorded:"付款資訊依國際協調時間（UTC）記錄，僅供參考。",
            problems:"若您付款時有任何問題，請聯繫客戶支援。",
            support:"客戶支援",
            coins:"@ 個金幣",
            details:"細節",
            cancel:"取消",
            confirm:"確認",
            days:"% 天 #",
            month:"1 個月 #",
            months:"% 個月 #",
            year:"1 年#",
            lifeTime:"終身 #",
            sorry:"抱歉，載入時發生問題。請稍後再試。",
            refesh:"刷新",
            noPayment:"沒有付款記錄",
            refreshBtn:"重新整理購買狀態",
            verification:"驗證進行中…",
            refreshBtns:"重新整理購買狀態（@s）",
            unsuccessful:"付款失敗",
            contact:"如果您有任何疑問，請聯繫我們。",
            ok:"OK",
            wait:"請稍候⋯⋯"
        },
        ko:{
            payment:"결제 이력",
            tap:"여기를 눌러 결제 이력을 보십시오",
            today:"오늘",
            successful:"결제 성공",
            failed:"결제 실패",
            pending:"대기 중",
            status:"상태:",
            price:"참고 가격:",
            time:"결제 시각:",
            method:"결제 수단:",
            number:"주문 번호:",
            recorded:"지불 정보는 UTC 시간으로 기록되며 참고용으로만 사용됩니다.",
            problems:"결제에 문제가 있는 경우 고객 지원에 문의하시기 바랍니다.",
            support:"고객 지원",
            coins:"@코인",
            details:"세부",
            cancel:"취소",
            confirm:"확인",
            days:"%일 #",
            month:"1개월 #",
            months:"%개월 #",
            year:"1년 #",
            lifeTime:"평생 #",
            sorry:"죄송합니다, 로드 중에 뭔가 잘못되었습니다. 나중에 다시 시도해 주세요.",
            refesh:"새로 고침",
            noPayment:"결제 이력 없음",
            refreshBtn:"구매 상태 새로고침",
            verification:"확인 진행 중…",
            refreshBtns:"구매 상태 새로고침 (@s)",
            unsuccessful:"결제 실패",
            contact:"질문이 있으시면 저희에게 연락하십시오.",
            ok:"확인",
            wait:"기다려 주세요..."
        }
}
export default data;